/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.android.myffmpegx264lib;

public class exampleEncoderInterfaceJNI {
  public final static native long new_exampleEncoder();
  public final static native void exampleEncoder_initialize(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_video_encode(long jarg1, exampleEncoder jarg1_, byte[] jarg2, int jarg3, int jarg4, byte[] jarg5, int[] jarg6);
  public final static native void exampleEncoder_close(long jarg1, exampleEncoder jarg1_);
  public final static native int exampleEncoder_getBitrate(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setBitrate(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native int exampleEncoder_getFps(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setFps(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native int exampleEncoder_getGopSize(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setGopSize(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native int exampleEncoder_getHeight(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setHeight(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native int exampleEncoder_getMaxBframes(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setMaxBframes(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native int exampleEncoder_getWidth(long jarg1, exampleEncoder jarg1_);
  public final static native void exampleEncoder_setWidth(long jarg1, exampleEncoder jarg1_, int jarg2);
  public final static native void delete_exampleEncoder(long jarg1);
}
