/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.android.myffmpegx264lib;

public interface frameEncoderInterfaceConstants {
  public final static int INBUF_SIZE = frameEncoderInterfaceJNI.INBUF_SIZE_get();
  public final static int AUDIO_INBUF_SIZE = frameEncoderInterfaceJNI.AUDIO_INBUF_SIZE_get();
  public final static int AUDIO_REFILL_THRESH = frameEncoderInterfaceJNI.AUDIO_REFILL_THRESH_get();
}
