/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.android.myffmpegx264lib;

public class frameEncoderInterfaceJNI {
  public final static native int INBUF_SIZE_get();
  public final static native int AUDIO_INBUF_SIZE_get();
  public final static native int AUDIO_REFILL_THRESH_get();
  public final static native long new_frameEncoder();
  public final static native void delete_frameEncoder(long jarg1);
  public final static native boolean frameEncoder_open(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_encodeFrame(long jarg1, frameEncoder jarg1_, byte[] jarg2, int jarg3, int jarg4, byte[] jarg5, int[] jarg6);
  public final static native boolean frameEncoder_close(long jarg1, frameEncoder jarg1_);
  public final static native boolean frameEncoder_validateSettings(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setParams(long jarg1, frameEncoder jarg1_);
  public final static native int frameEncoder_getFps(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setFps(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getInHeight(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setInHeight(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getInWidth(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setInWidth(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getNumNals(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setNumNals(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getOutHeight(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setOutHeight(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getOutWidth(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setOutWidth(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getBitrate(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setBitrate(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getSliceMaxSize(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setSliceMaxSize(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getVbvBufferSize(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setVbvBufferSize(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getIThreads(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setIThreads(long jarg1, frameEncoder jarg1_, int jarg2);
  public final static native int frameEncoder_getBFrameFrq(long jarg1, frameEncoder jarg1_);
  public final static native void frameEncoder_setBFrameFrq(long jarg1, frameEncoder jarg1_, int jarg2);
}
